### ISSUE TITLE
Provide linux binaries

### ISSUE THREAD

**Issue by Mistera91** [jd-develop/nougaro#8]
(please)

**Comment by jd-develop** [comment]
Is this one works ? Could you test with 'math' module please ?
Thank you :)

[nougaro-1d3268e2e374c5edaa22e229d27bdb43e3c816d3-linux-bin.tar.gz](https://github.com/jd-develop/nougaro/files/10020145/nougaro-1d3268e2e374c5edaa22e229d27bdb43e3c816d3-linux-bin.tar.gz)

**Comment by jd-develop** [comment]
Nope, doesn't work with `math`, `statistics`, `time` and `random` modules. I'll check why

**Comment by Mistera91** [comment]
You want a ssh to try it out ?

**Comment by jd-develop** [comment]
nope, its ok, i can test with WSL ^^

**Comment by jd-develop** [comment]
provided in 0.10 ^^
